plugins: [jekyll-paginate]

collections:
  authors:
    output: true
  gats:
    output: true

defaults:
  - scope:
      path: ""
      type: "gats"
    values:
      layout: "gat"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: /blog

paginate: 10
paginate_path: "/page:num/"